### ISSUE TITLE
Improvement Suggestions

### ISSUE THREAD

**Issue by khaf** [bpaquet/aerodis#1]
Hi Bertrand, I'm the Go Client's dev from Aerospike.

Thanks for open-sourcing this program.

I just noticed that you are using UDF functions for a lot of functionality that is supported out of the box in Aerospike. Native operations are much faster and more reliable.

- For reference kindly have a look at `ListxxxOp` and `MapxxxOp` API. Best of all, they can all be sent via a single `Operate` command in a batch, without the need to do multiple calls.

- TTL's don't need to be passed as values to the functions. They are a part of `WritePolicy`

- You can use type switches instead of reflection for deciding the type of interfaces. Much faster and easier on the memory.

- There are a few instances of reading from a `conn` without checking how many bytes were read. `io.ReadFull` will help.

- `write_func` can use a `bytes.Buffer` to simply keeping its internal state.

- No license is provided. An Apache or BSD license will help others use and contribute to the code base.

Cheers,
K.

**Comment by bpaquet** [comment]
Thanks you for reviewing the project. I really appreciate.

My answers below.

Le lun. 21 nov. 2016 à 01:45, Khosrow Afroozeh <notifications@github.com> a
écrit :

> Hi Bertrand, I'm the Go Client's dev from Aerospike.
>
> Thanks for open-sourcing this program.
>
> I just noticed that you are using UDF functions for a lot of functionality
> that is supported out of the box in Aerospike. Native operations are much
> faster and more reliable.
>
>    - For reference kindly have a look at ListxxxOp and MapxxxOp API. Best
>    of all, they can all be sent via a single Operate command in a batch,
>    without the need to do multiple calls.
>    -
>
>    TTL's don't need to be passed as values to the functions. They are a
>    part of WritePolicy
>
>
I just rewritten the wrapper from PHP to Go. Yes, there are probably some
improvements to do with the new Api (most of the code were written one year
ago), and with the Go Api. I will try to have a look.

>
>    -
>    -
>
>    You can use type switches instead of reflection for deciding the type
>    of interfaces. Much faster and easier on the memory.
>

Done.

>
>    There are a few instances of reading from a conn without checking how
>    many bytes were read. io.ReadFull will help.
>
Which one ?
>    write_func can use a bytes.Buffer to simply keeping its internal state.
>
What do you mean ?

>
>    No license is provided. An Apache or BSD license will help others use
>    and contribute to the code base.
>

Done.

**Comment by khaf** [comment]
Hi Bertrand, thank you for taking the time to fix the issues. I've clarified some of the suggestions I had below:

>> There are a few instances of reading from a conn without checking how many bytes were read. io.ReadFull will help.

> Which one ?

https://github.com/bpaquet/aerodis/blob/master/protocol.go#L54

I guess this is the reason for https://github.com/bpaquet/aerodis/issues/3

>> write_func can use a bytes.Buffer to simply keeping its internal state.

> What do you mean ?

Sorry, I meant to simplify managing its state. Since you are only reading and writing serially to the buffer, there's no need to do the house keeping for the buffer.

A suggestion I have regarding testing is to test via the Redis client for Go. Make it connect to this library, and pass its own tests (if they actually connect to a Redis server), or you write the test cases yourself. No need for tests in PHP.
