### ISSUE TITLE
Client error: Unknown command while using Doctrine cache framework

### ISSUE THREAD

**Issue by morokin** [bpaquet/aerodis#3]
Hi, we're using Doctrine cache framework with namespaces to communicate with redis, when I using aerodis as a dropin replacement with no changes to code, I stuck with "Unknown command" and "Protocol error" errors:

**Example 1:**
aerodis output
```
2016/11/29 12:09:07 [test]  Client error : Unknown command 'MGET' {MGET, test_namespace[0:399:354:some_data:CA][1]}
2016/11/29 12:09:07 [test]  Client error : Unknown command 'espa' {espa, 1:654:some_data:CA:4][1]
$52
test_nam}
2016/11/29 12:09:07 [test]  Client error : Protocol error {, }
2016/11/29 12:09:07 [test]  Client error : Unknown command 'espa' {espa, 2:596:some_other_data:CA:4][1]
$57
test_nam}
```
**Example 2:**
tcpflow output of the real exchange with redis:
```

127.000.000.001.55544-127.000.000.001.06382: *2
$3
GET
$37
DoctrineNamespaceCacheKey[test_namespace]

127.000.000.001.55544-127.000.000.001.06382: *2
$4
INCR
$60
test_namespace[1:482:354:some_data:CA:3][1]

127.000.000.001.47042-127.000.000.001.06382: *2
$4
INCR
$52
test_namespace[1:351:491:some_other_data:CA:3][1]

```

**Comment by bpaquet** [comment]
I will implement mset / mget, not very complicated.

Bertrand

Le mar. 29 nov. 2016 à 04:50, Morokin Evgeny <notifications@github.com> a
écrit :

**Comment by morokin** [comment]
Hi Bertrand, I tested everything after last commits, looks like mset/mget implementation did not solve the issue. I'm not quite sure is it related to aerodis redis protocol implementation, or to Doctrine itself. We're using http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/caching.html#redis and http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/caching.html#namespaces

As you can see from the output examples aerodis somehow splits commands and keys and considers it as erroneous command.

I appreciate any advice.

Evgeny

**Comment by khaf** [comment]
this may be related to this line:

https://github.com/bpaquet/aerodis/blob/master/protocol.go#L54

Change it to:

```go
l, err := io.ReadFull(ctx.conn, ctx.buf[ctx.end:])
```

and see if it fixes your problem.

**Comment by morokin** [comment]
```
# go build
# aerodis
./protocol.go:54: undefined: io in io.ReadFull

```

**Comment by khaf** [comment]
You have to add "io" to the list of imports at the top of the file.

**Comment by morokin** [comment]
> You have to add "io" to the list of imports at the top of the file.

I did it already ), let me check how it will work

**Comment by morokin** [comment]
Output changed:
```
2016/12/05 11:51:54 [aerodis]  Client error : unexpected EOF {, }
2016/12/05 11:51:54 [aerodis]  Client error : unexpected EOF {, }
```

**Comment by bpaquet** [comment]
Do you have a piece of PHP code which highlight the problem ?

**Comment by morokin** [comment]
Hi Bertrand, here below results of last tests:

<details>
  <summary>Click to expand</summary>

I recompiled the aerodis as you suggested above and only one error left:

```
2016/12/08 18:31:21 [aerodis]  Client error : unexpected EOF {, }
```

Then:
I grabbed a piece of test code from [here](https://www.tutorialspoint.com/redis/redis_php.htm)

```
<?php
   //Connecting to Redis server on localhost
   $redis = new Redis();
   $redis->connect('127.0.0.1', 6379);
   echo "Connection to server sucessfully";
   //set the data in redis string
   $redis->set("tutorial-name", "Redis tutorial");
   // Get the stored data and print it
   echo "Stored string in redis:: " .$redis→get("tutorial-name");
?>
```

**Expected output:**
```
Connection to server sucessfully
Stored string in redis:: Redis tutorial
```

**Output from script:**
```
$ php test2.php 
Connection to server sucessfully
PHP Fatal error:  Uncaught RedisException: read error on connection in /user/aerodis/test2.php:7
Stack trace:
#0 /user/aerodis/test2.php(7): Redis->set('tutorial-name', 'Redis tutorial')
#1 {main}
  thrown in /user/aerodis/test2.php on line 7
```

**Output from aerodis:**
`2016/12/08 18:31:21 [aerodis]  Client error : unexpected EOF {, }`

Then I did a second test:
```
$ time php test2.php
real    1m0.084s
user    0m0.016s
sys     0m0.025s

$ php -i | grep default_socket_timeout
default_socket_timeout => 60 => 60
```

Every time after test script execution aerodis throws error listed above, so on my opinion it related to connection closing. But something definitely going wrong since I'm able to open connection to aerodis but receiving socket timeout after this.


Have a great day and please let me know if you need any additional information.

</details>

**Comment by khaf** [comment]
Did you update to the latest master? I can't reproduce this after the latest changes.

**Comment by bpaquet** [comment]
It's a very simple use case ...

Can you provide your phpinfo ? With something like  ``echo -ne "<?php\nphpinfo();" | php`` ? Which version of phpredis did you use ?
Can you provide a network dump ? ``tcpdump -i lo0 -w out.pcap port 6379`` ? (``lo`` on a linux)

**Comment by morokin** [comment]
Hi, as @khaf wrote, with latest master test code running without errors. Let me test everything with some real code. Appreciate your help.
